# Generated by Django 2.1.4 on 2019-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='book1',
            name='theatre',
            field=models.CharField(default='', max_length=250),
        ),
    ]
