# Generated by Django 2.1.4 on 2019-02-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190225_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book1',
            old_name='name',
            new_name='user',
        ),
    ]
