# Generated by Django 2.1.4 on 2019-03-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190225_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='available',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='seats',
        ),
    ]
